# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54f90e1c14798021098abc167e7d2fee0e57eb63d4bf0f957d342302a964a674da2b4041b55b497067e41ef47cf9ea1f7657dea091ad77f78d8917e05df0c6c

test:
  secret_key_base: e6d97f6735e8fe893d3c51aa55c7c93c6edf5e378db34d80db59bc9427b8da6e85107029381972794f197dad9b8a930fc7653e295bd07fe14f48a1403805311b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
